export { apiClient, configureApiClient } from './client';
export type * from './types';
export type { AttendanceSession, AttendanceRecord } from './attendance';
export type { InviteDetails } from './auth';
export * as authApi from './auth';
export * as adminApi from './admin';
export * as coachApi from './coach';
export * as teamsApi from './teams';
export * as chatApi from './chat';
export * as healthApi from './health';
export * as attendanceApi from './attendance';
export * as scheduleApi from './schedule';
export * as workoutApi from './workout';
export * as notificationsApi from './notifications';
export * as platformApi from './platform';
export type { PlatformAdmin, EnrollmentRequest, PlatformAcademy, PlatformStats } from './platform';
export { getPlatformToken, setPlatformToken, clearPlatformToken } from './platform';
export * as feesApi from './fees';
export * as documentsApi from './documents';
export * as announcementsApi from './announcements';
export * as analyticsApi from './analytics';
export type { FeeAnalytics, AttendanceAnalytics, WellnessAnalytics, MyWellnessAnalytics } from './analytics';
export type { FeeLedgerEntry, PlayerDocument, Announcement, UserPreferences, AcademyAdminSettings, NotificationPreferences } from './types';
